import React from "react";
import { useSelector } from "react-redux";
import { selectPools, selectPrices } from "../../state/poolsListSlice";
import { Pool } from "../../lib";
import Information from "../../components/Information";
import { formatPercent, numberToCompactCurrency } from "../../lib/numeric";

const PoolsInformation = (): JSX.Element => {
  const pools = useSelector(selectPools);
  const prices = useSelector(selectPrices);

  const getPrice = (pool: Pool) => prices[pool.underlying.symbol] || 0;
  const locked = pools.reduce((a: number, b: Pool) => a + b.totalAssets * getPrice(b), 0);
  const averageApy = pools.reduce((a: number, b: Pool) => a + b.apy, 0) / pools.length;

  return (
    <Information
      header="Pools Overview"
      rows={[
        {
          label: "Platform TVL",
          tooltip:
            "The market capitalization of total assets held in Backd liquidity pools (total value locked)",
          value: numberToCompactCurrency(locked),
        },
        {
          label: "Average APY",
          tooltip: "The average annual percent yield over a 30 day period",
          value: formatPercent(averageApy),
        },
        // {
        //   label: "Revenue",
        //   tooltip: "The total value of fees generated by the Backd protocol",
        //   value: "$0",
        // },
      ]}
    />
  );
};

export default PoolsInformation;
